module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Introduction',
      collapsible: false,
      items: ['ai-engineer-guide'],
    },
    {
      type: 'category',
      label: 'AI engineering fundamentals',
    collapsible: false,
      items: [
        'fundamentals',
        'llm-fundamentals',
        'prompt-engineering',
        'context-engineering',
        'fine-tuning',
        {
          type: 'category',
          label: 'RAG',
          collapsible: false,
          items: [
            'rag',
            'rag-patterns/basic-rag',
            'rag-patterns/agentic-rag',
            'rag-patterns/deep-search',
            'rag-patterns/grounded-generation',
            'rag-patterns/hybrid-retrieval',
            'rag-patterns/retrieval-refinement',
            'rag-patterns/semantic-indexing',
          ],
        },
        {
          type: 'category',
          label: 'AI Agents',
          collapsible: false,
          items: [
            'ai-agents',
            'agent-patterns/tool-calling',
            'agent-patterns/react-loop',
            'agent-patterns/plan-and-execute',
            'agent-patterns/multi-agent-collaboration',
            'agent-patterns/code-execution',
          ],
        },
        'mcp',
        'llm-optimization',
        'llm-evaluation',
        'llm-deployment',
        'llm-observability',
      ],
    },
    {
      type: 'category',
      label: 'Agentic AI frameworks',
      collapsible: false,
      items: [
        'agentic-frameworks',
        'frameworks/langchain',
        'frameworks/mastra',
        'frameworks/pydantic-ai',
      ],
    },
    // {
    //   type: 'category',
    //   label: 'Beyond the interview',
    //   collapsible: false,
    //   items: ['role-landscape', 'offer-negotiation', 'career-growth'],
    // },
  ],
};
